services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"   # script python 
      - "29092:29092" # communication interne Docker

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      - KAFKA_BROKERS=redpanda:29092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

  redis_cache:
    image: redis:7.2-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8002:8001"
    environment:
      - RI_APP_PORT=8001
    depends_on:
      - redis_cache

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - redpanda
    volumes:
      - ./data:/app/data

  spark_processor:
    build:
      context: .
      dockerfile: processing/Dockerfile
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - redpanda

  fraud_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis_cache

  dashboard:
    build: 
      context: ./web
    container_name: dashboard_ui
    ports:
      - "8501:8501"
    depends_on:
      - fraud_api
    environment:
      - API_URL=https://fraud_api:8000